# Generated by Django 2.2 on 2022-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('data', models.BinaryField()),
                ('state', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
